# -*- coding: utf-8 -*-
"""sum_of_list_element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-ZWVKia4O8MMVcZjIg4LzKGpn_jbD7m
"""

lst = [8, 2, 3, 0, 7]
sum = 0
for i in lst:
   sum += i
print(sum)